//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 05 20:23:01 CST 2013
//----------------------------------------------------

package simpl.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
    /* terminals */
    public static final int CONS = 31;
    public static final int ORELSE = 18;
    public static final int GE = 30;
    public static final int UNIT = 32;
    public static final int LPAREN = 38;
    public static final int SEMI = 37;
    public static final int REF = 3;
    public static final int RPAREN = 39;
    public static final int REC = 5;
    public static final int NOT = 16;
    public static final int LT = 27;
    public static final int FN = 4;
    public static final int NIL = 2;
    public static final int IN = 7;
    public static final int COMMA = 36;
    public static final int DIV = 22;
    public static final int NUM = 41;
    public static final int ASSIGN = 34;
    public static final int IF = 9;
    public static final int ID = 42;
    public static final int LE = 28;
    public static final int EOF = 0;
    public static final int APP = 40;
    public static final int TRUE = 14;
    public static final int error = 1;
    public static final int MUL = 21;
    public static final int ADD = 19;
    public static final int MOD = 23;
    public static final int EQ = 25;
    public static final int ARROW = 33;
    public static final int NEG = 24;
    public static final int ELSE = 11;
    public static final int ANDALSO = 17;
    public static final int WHILE = 12;
    public static final int LET = 6;
    public static final int THEN = 10;
    public static final int NE = 26;
    public static final int END = 8;
    public static final int FALSE = 15;
    public static final int GT = 29;
    public static final int SUB = 20;
    public static final int DEREF = 35;
    public static final int DO = 13;
}
